ALTER TABLE ZIPCODE_INFO
CITY VARCHAR(25),STATE VARCHAR(2)

ALTER TABLE ZIPCODE_INFO
CITY VARCHAR(25),STATE VARCHAR(2)

ALTER TABLE ZIPCODE_INFO
CITY VARCHAR(25),STATE VARCHAR(2)

ALTER TABLE ZIPCODE_INFO
CITY VARCHAR(25),STATE VARCHAR(2)

ALTER TABLE ZIPCODE_INFO
CITY VARCHAR(25),STATE VARCHAR(2)

ALTER TABLE ZIPCODE_INFO
CITY VARCHAR(25),STATE VARCHAR(2)

ALTER TABLE ZIPCODE_INFO
CITY VARCHAR(25),STATE VARCHAR(2)