--TABLE- ZIPCODE_INFO
create table ZIPCODE_INFO
(
ZIP_CODE VARCHAR(5),
CITY VARCHAR(10));

--TABLE- INSTRUCTOR_INFO
CREATE TABLE INSTRUCTOR_INFO
(INSTRUCTOR_ID INT,
INSTRUCTOR_FIRST_NAME VARCHAR(15),
INSTRUCTOR_LAST_NAME VARCHAR(15));

--TABLE- COURSE_INFO
CREATE TABLE COURSE_INFO
(COURSE_NO INT,COST INT);

--TABLE- STUDENT_INFO
CREATE TABLE STUDENT_INFO
(STUDENT_ID INT, STUDENT_FIRST_NAME VARCHAR(15),STUDENT_LAST_NAME VARCHAR(15));

--TABLE- SECTION_INFO
CREATE TABLE SECTION_INFO
(SECTION_ID INT,COURSE_NO INT,
SECTION_NO INT, INSTRUCTOR_ID INT)

  --TABLE- ENROLLMENT_INFO
CREATE TABLE ENROLLMENT_ID
(
STUDENT_ID INT, SECTION_ID INT)

--TABLE- GRADE_INFO
CREATE TABLE GRADE_INFO
( STUDENT_ID INT, SECTION_ID INT, GRADE_TYPE_CODE CHAR, GRADE_CODE_OCCURANCE INT)
