create table ZIPCODE_INFO
(
ZIP_CODE VARCHAR(5),
CITY VARCHAR(10));

CREATE TABLE INSTRUCTOR_INFO
(INSTRUCTOR_ID INT,
INSTRUCTOR_FIRST_NAME VARCHAR(15),
INSTRUCTOR_LAST_NAME VARCHAR(15));

ALTER TABLE INSTRUCTOR_INFO
ADD
STREET_ADDRESS VARCHAR(50),ZIP_CODE VARCHAR(5)

CREATE TABLE COURSE_INFO
(COURSE_NO INT,COST INT);

ALTER TABLE COURSE_INFO
ADD
COURSE_NAME VARCHAR(50),COURSE_PREREQUISITE INT

CREATE TABLE STUDENT_INFO
(STUDENT_ID INT, STUDENT_FIRST_NAME VARCHAR(15),STUDENT_LAST_NAME VARCHAR(15));


ALTER TABLE STUDENT_INFO
ADD
STREET_ADDRESS VARCHAR(50),ZIP_CODE VARCHAR(5)

CREATE TABLE SECTION_INFO
(SECTION_ID INT,COURSE_NO INT,
SECTION_NO INT, INSTRUCTOR_ID INT)

ALTER TABLE SECTION_INFO
ADD
LOCATION VARCHAR(50),CAPACITY INT

CREATE TABLE ENROLLMENT_ID
(
STUDENT_ID INT, SECTION_ID INT)

ALTER TABLE ENROLLMENT_ID
ADD
ENROLLMENT_DATE DATE

CREATE TABLE GRADE_INFO
( STUDENT_ID INT, SECTION_ID INT, GRADE_TYPE_CODE CHAR, GRADE_CODE_OCCURANCE INT)
ALTER TABLE GRADE_INFO
ADD 
 GRADE INT

ALTER TABLE ZIPCODE_INFO
ADD
STATE VARCHAR(2)